keys:
  - &athena age153ntk5rhvdme8sxswgfnphwkyzvk3ucrjaf0lr8wl33p6lpca5fs2w0u27
  - &nimeses age1n4geasdvfp79tuzyv6czdm68p5u6s8nawjnkv2xu46s9daxju9sse0khsc
creation_rules:
  - path_regex: secrets/athena\.yaml$
    key_groups:
      - age:
          - *athena
          - *nimeses
  - path_regex: secrets/nimeses\.yaml$
    key_groups:
      - age:
          - *nimeses
